### ISSUE TITLE
Trouble to make it work

### ISSUE THREAD

**Issue by PlkMarudny** [nickheal/svelte-tour#12]
Hi, look at this [REPL](https://svelte.dev/repl/6995513de6144fe4acc7e3c31d3effa3?version=3.37.0), please. It does not seem to work in a simple setup. What am I doing wrong?

**Comment by nickheal** [comment]
Hi @PlkMarudny thanks for flagging this. There's a couple of things I've noticed.

1. I need to update the readme, because the Tour component now needs a TourTip provided as an argument (a default one is provided in the package).
2. It looks like in that example run isn't being called as a function? It should be `run()` rather than `run`.

**Comment by nickheal** [comment]
This should now be fixed as a result of this pr: https://github.com/nickheal/svelte-tour/pull/17

Running the following code in your REPL should now work:
```javascript
<script>
	import {Tour, TourItem, TourTip, run} from 'svelte-tour';
	
	function handleTour() {
		run();
	}
	
</script>

<main>
<Tour TourTip={TourTip}></Tour>
<button on:click={() => handleTour()}>
	tour
</button>

<TourItem message="header h1">
	<h1>Hello world!</h1>
</TourItem>
<TourItem message="header h2">
	<h2>
	sth else
</h2>
</TourItem>
</main>
```
